package exFor;

public class Ex5 {
    public static void main(String[] args) {
        System.out.println("""
                       ┳┳┓  ┓ •  ┓      ┓    ┏┓             ┓      ┓┏┓┏┓┏┓
                       ┃┃┃┓┏┃╋┓┏┓┃┏┓┏  ┏┫┏┓   ┫  ┏┓┏┓╋┏┓┏┓  ┃  ┏┓  ┃┃┫┃┫┃┫
                       ┛ ┗┗┻┗┗┗┣┛┗┗┛┛  ┗┻┗   ┗┛  ┗ ┛┗┗┛ ┗   ┻  ┗┻  ┻┗┛┗┛┗┛
                               ┛\s
        """);
        for (int count = 0; count <= 1000; count++) {
            if (count % 3 == 0) {
                System.out.println(count);
            }
        }
        System.out.println("""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXKKXNNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0kxdoollcc:::;;;::clodxO000KKKKXXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdc:,'......................',:lodddddddddxkO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'...............................,;;;;;:::;;,;;:ccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.................................,;;;,''''''''''',lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.................................,;;;'..........,:;:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.................................,;:,...........',,.'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo..................................,;;'................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,..................................,;,'................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...................................,,,.................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,..................................',,,'................kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKd:::;;:::::::;,,;,,;;;;;,'.',;,''.'',,,,,,;;;;;;;;;;,,'.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMWNXK00000OOkkkkkkkxxdddooooolooolloooodxdoolcc:;'''',,,;,,,,,,,,,''oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWNWMWNKOkkkkkkOOOOOOOOOOOOOOOkkkkxxxxxxxxxxxxxkOxolll:;,''',,,,,''''''''''.cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNKkollloddddddxxxxxxxkkkOO0K00OOkkxxxddooolllolc:;;,,,,'',,,,,'',,,,,,,,,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXd::::::;:cccccccclloddxxk00Okxxdoollcc::::;,;;,,,',,,,''',,,,,,,,,,,,,,,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXl,,,;:;;:ccccccccccccccccccccccc:::;;;;;,,,,,,,,'',,,''''',,,,,,,,,,,,;:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWk:',,;;,;:::::;;;;::;;;;;;;;;;;;;;,,,,,,,,',,'',,'',,,'''',,,,,,,,,,;;;::xNMMMMMMMMMMMMMMMMMMWNNNNNNWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXl,,,'',,,;;;;;:::::;,;;;;;;;;;;,,,,,,,,,,''''.'',,''''''''',,,,,,,;;;;;::xNWKkxxO0000K0OkdollllcllooddddoddooOKK00KWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMO:,,''''''',,,;;;;;:;,,;::::::;;;;;;;;;;;,;:::cccccccc:::;;;;,,,,,,,;;;;;:oOd;''',:::::;;;;;;;ccc::;,,,,;;,'.':cccdKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNd,............'',,;;;:cllodddoooooooollc:clllllccc:::;,''''''',,,,,,,;;;:,......';:clcc:;;;,,'',''''',''....'....'dXWWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0c.....';;'.......'''.'',,;::::::::::;;;;;;;,,,,,''''''..........'',,;;;:cc:;,;clloddool:'.'''.':::;'.............'lxxKMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKc.....;;,;'....,,'.......',,,,;,,,,,,,,,,,,,,'',',;,'.....'......''',;:::::;,,;cllcc::;;;::;,,:lol;'.............'kWNWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKc.'..';c:;'..',,'......,llodlc;,,,,,,,,,,,,,'',,cdc'...............',coc'.''''.''''''',,,'.....,;:;'.............'kMWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKl,...';',,..','.......,lldO0kdl;,,,,,,,,,,''...,c;...''.............,:lc'.'''........,:::;;;,;:lodo;.............,OWWWMMMMMMMMMMMM
MMMMMMMMMMMMMMWNNNKdlc:,'''...','.........'lddOKOxo:,,,,,,,,,''.........'................;cc;;;;,.......';;;:::cccclllo:.............cXWWWWMMMMMMMMMMM
MMMMMMMMMMMMMMKdkKklc:;::;;,,,,,'..........'oxxxoc;,,,;;,,,,'..........'.................':lodxdc::;;;;;::::::cccllloool,...........,OWWWWWMMMMMMMMMMM
MMMMMMMMMMMMMM0;.;cc:'.....'',;;;;;;;;;;;,,;;:::;;;;;;;;,,,'..........'...................;lolclc:cccccccllllooodddddxxxdc:;;:;,'..;kNWWWWMMMMMMMMMMMM
MMMMMMMMMMMMMMNo....................',;::::cccccc:;;;;,,,''..........'.....................,,.'::cclloodddxxxkkOOOOOOO0000000KK0000XWWWWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO'................';::::;;,,'''''''.....'',,,,........'.....................;:::cclodxxkOO000KKKXXXXXXXXXXXXXNNNNNWWWWWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO,'';c,.,'..........',;:cclcccccllc:::;;;:;;;,.......'........'''''.........;ccllodxkO0KKXXNNNNWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMKo:ccl,cK0kdl:'...............''','..................'......'''...''........;lodxkO0KXXNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWXOdlc,ckKXNNXx'....................................'........'..............:xkO0KXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWX0xollodxko'',..........'''''....'''''..''..............''..............lO0KXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWNKOxdolc:::;,'.',..,clllc:::;;;::::,.;:'...............''''..........oXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWWNXX0Oxdollllc:::;,;clllcc:::::cccc:,:c,.......................coooloONWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWWNNXK00Oxdollcccllcclollllllllllooddodd:......................lO0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWWWWNNXK0Okxdoolccccccccllllllllllllllcc:'...................'o0XXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXK0Okxxdooolllllcccccc:::::::cccc;.................;kXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXK00OOkkxxxdddooooollllllloooool;,...........,cxKNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXKK000OOOkkkkxxxxxxxxxxxxxxkkxolc::codxOKNWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNXXXXKKKKK000000000000000KKXXXNNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNNNNNNNNXXXXXXXXXXNNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                """);
    }
}
